name = "Glicko"
uuid = "00770c93-6ee5-40d7-9659-5e965860069a"
authors = ["Fernando Miguel Hahne <fernandomhahne@gmail.com>"]
version = "0.1.0"

[deps]
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
Roots = "2.0"
julia = "1.9"
